# icon =
# min_score =
hide_from_providerlist = false
# launch_prefix =
# locale =
# action_min_score = 20
show_actions = false
show_generic = false
show_actions_without_query = false
# history = true
history_when_empty = true
# only_search_title =
# icon_placeholder =
# aliases =
blacklist = [
    "assistant",
    "avahi-discover",
    "bssh",
    "btop",
    "bvnc",
    "calibre-ebook-edit",
    "calibre-ebook-viewer",
    "calibre-gui",
    "calibre-lrfviewer",
    "cmake-gui",
    "designer",
    "electron34",
    "electron37",
    "fcitx5-configtool",
    "foot-server",
    "foot",
    "footclient",
    "imv-dir",
    "imv",
    "jconsole-java-openjdk",
    "jshell-java-openjdk",
    "kbd-layout-viewer5",
    "linguist",
    "mpv",
    "nm-connection-editor",
    "nvidia-settings",
    "nvim",
    "org.fcitx.fcitx5-migrator",
    "org.fcitx.Fcitx5",
    "org.gnome.Evince",
    "org.pulseaudio.pavucontrol",
    "qalculate-gtk",
    "qdbusviewer",
    "qv4l2",
    "qvidcap",
    "uuctl",
    "vim",
    "xgps",
    "xgpsspeed",
]
