[[entries]]
default = true
name = "Google"
url = "https://www.google.com/search?q=%TERM%"
icon = "web-google"

[[entries]]
name = "Github"
url = "https://github.com/search?q=%TERM%&type=repositories"
icon = "github"
