set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{HOME}/.local/share/tmux/plugins/'

source ~/.config/tmux/tpm.conf
source ~/.config/tmux/bindings.conf
source ~/.config/tmux/plugins.conf
source ~/.config/tmux/themes/catppuccin.conf

# Tmux plugins configuration
set -g @continuum-boot 'on'

# General configuration
set -g allow-rename off
set -g mouse on
set -g status-left-length 100
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-window on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm'
