# icon =
# min_score =
hide_from_providerlist = false
# launch_prefix =
# locale =
# action_min_score = 20
# show_actions = false
# show_generic = true
# show_actions_without_query = false
# history = true
history_when_empty = true
# only_search_title =
# icon_placeholder =
# aliases =
# blacklist =
