exec-once = hypridle
exec-once = mako
exec-once = fcitx5
exec-once = waybar
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-clip-persist --clipboard regular & clipse -listen
exec-once = dropbox-cli start
exec-once = walker --gapplication-service
exec-once = nm-applet
