source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/keywords.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/envs.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windowrule.conf