source = ~/.config/hypr/conf/envs.conf
source = ~/.config/hypr/conf/autostart.conf

# Interface
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/misc.conf

# Inputs, outputs and devices
source = ~/.config/hypr/conf/device.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/monitors.conf

# Binds and rules
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windowrule.conf

# Layouts and plugins
source = ~/.config/hypr/conf/layouts/dwindle.conf
source = ~/.config/hypr/conf/layouts/master.conf
source = ~/.config/hypr/conf/plugins.conf