name = "system"
name_pretty = "System"
icon = "system"
history_when_empty = false
fixed_order = true
hide_from_providerlist = true

[[entries]]
text = "Lock"
actions = { "lock" = "hyprlock" }
icon = "lock"

[[entries]]
text = "Suspend"
actions = { "suspend" = "systemctl suspend" }
icon = "system-suspend"

[[entries]]
text = "Relaunch"
actions = { "relaunch" = "uswm stop" }
icon = "wayland"

[[entries]]
text = "Restart"
actions = { "restart" = "systemctl reboot" }
icon = "system-restart"

[[entries]]
text = "Shutdown"
actions = { "shutdown" = "systemctl poweroff" }
icon = "kshutdown"
