exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = uwsm app -- waybar
exec-once = ~/.config/hypr/scripts/swaybg.sh abstract-1.png
exec-once = uwsm app -- walker --gapplication-service
exec-once = uwsm app -- swayosd-server
