exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = uwsm app -- waybar
exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/awww.sh
exec-once = uwsm app -- walker --gapplication-service
exec-once = uwsm app -- swayosd-server
exec-once = hyprpm reload -nn
