exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = uwsm app -- waybar
exec-once = uwsm app -- fcitx5 -d
exec-once = ~/.config/hypr/scripts/swaybg.sh abstract-1.png
exec-once = uwsm app -- systemctl --user start hyprpolkitagent
exec-once = uwsm app -- dropbox-cli start
exec-once = uwsm app -- elephant
exec-once = uwsm app -- walker --gapplication-service
# exec-once = uwsm app -- nm-applet
exec-once = uwsm app -- swayosd-server
