input {
    # kb_model = 
    # kb_layout = us
    kb_variant = intl
    kb_options = compose:ralt
    # kb_rules = 
    # kb_file = 
    numlock_by_default = true
    # resolve_binds_by_sym = false
    # repeat_rate = 25
    # repeat_delay = 600
    # sensitivity = 0.0
    # accel_profile = 
    # force_no_accel = false
    # rotation = 0
    # left_handed = false
    # scroll_points = 
    # scroll_method = 
    # scroll_button = 0
    # scroll_button_lock = false
    # scroll_factor = 1.0
    # natural_scroll = false
    # follow_mouse = 1
    # follow_mouse_threshold = 0.0
    # focus_on_close = 0
    # mouse_refocus = true
    # float_switch_override_focus = 1
    # special_fallthrough = false
    # off_window_axis_events = 1
    # emulate_discrete_scroll = 1

    touchpad {
        # disable_while_typing = true
        # natural_scroll = false
        # scroll_factor = 1.0
        # middle_button_emulation = false
        # tap_button_map = 
        # clickfinger_behavior = false
        # tap-to-click = true
        # drag_lock = 0
        # tap-and-drag = true
        # flip_x = false
        # flip_y = false
        # drag_3fg = 0
    }
}

device {
    name = logitech-mx-master-3-1
    sensitivity = 0
}
