input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options = compose:ralt
    kb_rules =

    numlock_by_default = true

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

# gestures {
#     workspace_swipe = false
# }

device {
    name = logitech-mx-master-3-1
    sensitivity = 0
}
