# LG Ultrawide Landscape (primary)
monitor=HDMI-A-1, 2560x1080, 0x0, 1

# Dell Landscape (secondary)
monitor=HDMI-A-2, 1920x1080, auto-left, 1

# Dell Landscape (primary)
# monitor=HDMI-A-1, 1920x1080@60, 0x0, 1

# LG Ultrawide Portrait (secondary)
# monitor=HDMI-A-2, 2560x1080@60, auto-left, 1
