# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Float and center pavucontrol
windowrule = center, class:^(org.pulseaudio.pavucontrol)$
windowrule = float, class:^(org.pulseaudio.pavucontrol)$

# Float and center file pickers
windowrule = center, class:^([xX]dg-desktop-portal-gtk)$
windowrule = float, class:^([xX]dg-desktop-portal-gtk)$
windowrule = noblur, class:^([xX]dg-desktop-portal-gtk)$
windowrule = noborder, class:^(Xdg-desktop-portal-gtk)$
windowrule = size 1000 600, class:^([xX]dg-desktop-portal-gtk)$

# Telegram
windowrule = float, class:org.telegram.desktop
windowrule = center, class:org.telegram.desktop
windowrule = size 400 700, class:org.telegram.desktop

# TopTracker
windowrule = center, title:TopTracker
windowrule = noborder, title:TopTracker
windowrule = monitor 0, title:TopTracker

# Gnome Calendar
windowrule = float, class:org.gnome.Calendar
windowrule = center, class:org.gnome.Calendar

# Qalculate
windowrule = float, class:qalculate-gtk
windowrule = center, class:qalculate-gtk

# nmtui
windowrule = float, title:nmtui
windowrule = center, title:nmtui

# Special Workspace
windowrule = bordercolor rgb(f9e2af), onworkspace:s[true]

# Jetbrains
windowrule = noinitialfocus, class:(jetbrains-phpstorm), title:^win(.*)
windowrule = rounding 0, class:(jetbrains-phpstorm), title:^win(.*)
