# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Float and center pavucontrol
windowrule = center, class:^(org.pulseaudio.pavucontrol)$
windowrule = float, class:^(org.pulseaudio.pavucontrol)$

# Float and center file pickers
windowrule = center, class:Xdg-desktop-portal-gtk
windowrule = float, class:Xdg-desktop-portal-gtk
windowrule = noblur, class:Xdg-desktop-portal-gtk
windowrule = noborder, class:Xdg-desktop-portal-gtk

windowrule = center, class:Rofi

# Telegram
windowrule = float, class:org.telegram.desktop
windowrule = center, class:org.telegram.desktop
windowrule = size 400 700, class:org.telegram.desktop

# Force chromium into a tile to deal with --app bug
windowrule = tile, class:^(Chromium)$

# TopTracker
windowrule = move onscreen 40% 0%, initialTitle:^(Current Activity Description)$
windowrule = monitor 0, initialTitle:^(Current Activity Description)$
windowrule = noinitialfocus, initialTitle:^(Current Activity Description)$

# Gnome Calendar
windowrule = float, class:org.gnome.Calendar
windowrule = center, class:org.gnome.Calendar
