# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# Float and center pavucontrol
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, center on, float on, size 800 500

# Float and center file pickers
windowrule = match:class ^([xX]dg-desktop-portal-gtk)$, center on, float on, no_blur on, border_size = 0, size 1000 600

# Telegram
windowrule = match:class org.telegram.desktop, center on, float on, size 400 700

# TopTracker
windowrule = match:class TopTracker, center on, monitor 0

# Gnome Calendar
windowrule = match:class org.gnome.Calendar, center on, float on, size 1200 700

# Qalculate
windowrule = match:class qalculate-gtk, center on, float on, size 900 600

# nmtui
windowrule = match:title nmtui, center on, float on, size 1000 600

# Special Workspace
windowrule = match:workspace s[true], border_color rgb(f9e2af)

# Jetbrains
windowrule = match:class (jetbrains-phpstorm), match:title ^win(.*), no_blur on, no_initial_focus on, rounding 0
